# Generated by Django 6.0.1 on 2026-03-11 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=10)),
                ('idade', models.IntegerField(default=10)),
                ('sexo', models.CharField(max_length=255)),
                ('qualidade', models.CharField(choices=[('B', 'Bom'), ('R', 'Ruin'), ('O', 'Otimo')], default='B', max_length=1)),
                ('dt_nascimento', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='foto_perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_filme', models.CharField(max_length=255)),
                ('episodios', models.CharField(max_length=255)),
                ('qd_filme', models.CharField(choices=[('B', 'Bom'), ('R', 'Ruin'), ('O', 'Otimo')], default='O', max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temporada', models.CharField(max_length=255)),
                ('sobre', models.TextField(blank=True, null=True)),
                ('dt_lancamento', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.clientes')),
            ],
        ),
    ]
