# Generated by Django 6.0.1 on 2026-02-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_alter_clientes_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='dt_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
