# Generated by Django 6.0.1 on 2026-02-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_clientes_dt_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foto_perfil'),
        ),
    ]
